### ISSUE TITLE
Use of devel branch?

### ISSUE THREAD

**Issue by traversaro** [robotology/walking-teleoperation#101]
At the moment the robotology-superbuild assumes that this repo is using a `devel` branch for experimental features (see https://github.com/robotology/robotology-superbuild/blob/53815f532b824e43c1766fef506e68adaad874d5/cmake/ProjectsTagsUnstable.cmake#L36). However, since yesterday the unstable builds are failing as the `devel` branch of walking-teleoperation is not existing anymore (see https://github.com/robotology/robotology-superbuild/issues/1139#issuecomment-1152028625). 

Did the workflow on this repo changed and so the robotology-superbuild should be changed to point to master also for unstable changes? If that is the case, it would be anyhow convenient to recreate the `devel`  branch in the repo until the superbuild is changed.

**Comment by traversaro** [comment]
fyi @S-Dafarra @GiulioRomualdi

**Comment by S-Dafarra** [comment]
Sorry about that, that's my fault. Since ``master`` and ``devel`` were aligned, I silently shifted to the ``master`` + ``release`` policy. I just created again the ``devel`` branch, but I would remove it again when the ``superbuild`` changes.

**Comment by traversaro** [comment]
Related PR: https://github.com/robotology/robotology-superbuild/pull/1160 .

**Comment by traversaro** [comment]
Fixed by https://github.com/robotology/robotology-superbuild/pull/1160 .

**Comment by S-Dafarra** [comment]
``devel`` branch deleted
