### ISSUE TITLE
Update licensing info to mention that the code is licensed under LGPL2  or any later version

### ISSUE THREAD

**Issue by traversaro** [robotology/walking-teleoperation#16]
The LICENSE file just mention LGPL3. I think it is ok to just mention a single license in the license file, but somewhere else (such as headers file or documentation) we should mention that the code is licensed actually under LGPL2 or any later version.

**Comment by kouroshD** [comment]
added in this branch: https://github.com/kouroshD/walking-teleoperation/tree/feature/updateDocs

**Comment by kouroshD** [comment]
The licensing info is added to the `devel` branch of repo by merging PR https://github.com/robotology/walking-teleoperation/pull/32. So, I close this issue.
Soon, we will merge the `devel` to `master`.
