### ISSUE TITLE
Shorter pipeline and startup enhancements

### ISSUE THREAD

**Issue by mebbaid** [robotology/walking-teleoperation#2]
As pointed out to me during the IROS demo, some tweaks to the way the application is run/started-up can be done, the main issues to address are:

- [ ] Try to run the `calibcams` automatically with the applications.
- [x] Manage ports connections in a better way
- [x] Manage the interconnection between the software and the `walking-controllers` in a smarter way
- [x] Investigate the possibility of throwing warnings instead of errors where appropriate (e.g. fingers hardware fault)

**Comment by kouroshD** [comment]
During the last months, we have improved and robustified the teleoperation pipeline. Therefore, we can close this issue.

CC @DanielePucci  @GiulioRomualdi
