### ISSUE TITLE
Add CI for walking-teleoperation repo

### ISSUE THREAD

**Issue by kouroshD** [robotology/walking-teleoperation#29]
I have the documentation here for adding CI for this repo.

https://github.com/mbonaci/mbo-storm/wiki/Integrate-Travis-CI-with-your-GitHub-repo

However, it is slightly different wrt what I have seen in settings.
@traversaro

**Comment by traversaro** [comment]
For new repos, I think GitHub Actions is more straightforward  to set up and maintain then Travis CI, but feel free to use the service that you prefer. 
I think the easier option to get up and running is to take scripts for similar repos and modify them to adapt them to your needs, see for example: 

Travis: 
* https://github.com/robotology/wb-toolbox/blob/v5/.travis.yml
* https://github.com/robotology/wearables/blob/v1.0.0/.travis.yml

GitHub Actions: 
* https://github.com/robotology/icub-tests/blob/master/.github/workflows/ci.yml
* https://github.com/dic-iit/bipedal-locomotion-controllers/blob/master/.github/workflows/ci.yml

**Comment by kouroshD** [comment]
the implementation of the CI can be found in the following branch: https://github.com/kouroshD/walking-teleoperation/tree/feature/Actions

**Comment by kouroshD** [comment]
The PR has been merged.
