### ISSUE TITLE
Release new version?

### ISSUE THREAD

**Issue by traversaro** [robotology/walking-teleoperation#49]
The problem fixed in https://github.com/robotology/walking-teleoperation/pull/48 means that the 0.2.0 version is not compatible anymore with iDynTree 3.0.0 . As there have been a few fixes since the latest release and a few interesting developments, could it make sense to merge https://github.com/robotology/walking-teleoperation/pull/47, and then do a new release?

cc @S-Dafarra @kouroshD @GiulioRomualdi

**Comment by S-Dafarra** [comment]
I agree

**Comment by kouroshD** [comment]
Sure, in a few days I will review and merge the PR and do a release.

**Comment by traversaro** [comment]
As https://github.com/robotology/walking-teleoperation/pull/47 was merged, probably now we can merge devel in master and do a release?

**Comment by traversaro** [comment]
Done in https://github.com/robotology/walking-teleoperation/releases/tag/v1.0.0, thanks @kouroshD !

**Comment by kouroshD** [comment]
I have to merge the devel to master and make a new release mainly related to xprize feb demo. I'll try to do it today.
