### ISSUE TITLE
Map Oculus buttons into defined YARP commands

### ISSUE THREAD

**Issue by GiulioRomualdi** [robotology/walking-teleoperation#5]
It would be nice to map the joypad oculus buttons to defined YARP commands. E.g.
* A + B `calib all 300`
* X + Y `startWalking`
* A + X reset the inertial frame of the robot. 
* ...

In my opinion, this may simplify the setup of the demo.

**Comment by traversaro** [comment]
Are this mappings documented somewhere?

**Comment by DanielePucci** [comment]
CC @GiulioRomualdi
