### ISSUE TITLE
Use space instead tab and remove trailing spaces

### ISSUE THREAD

**Issue by GiulioRomualdi** [robotology/walking-teleoperation#6]
I've noticed that there are some files (E.g., [`OculusModule.cpp`](https://github.com/robotology/walking-teleoperation/blob/master/modules/Oculus_module/src/OculusModule.cpp)) use tabs instead of spaces. 
As detailed described [here](https://www.emacswiki.org/emacs/TabsAreEvil) tabs are evil because different ide may have a different definition of tabs. Using spaces instead of tabs is also useful when several developers want to contribute to the code.

If you want I can propose a PR where all the tabs are substitute by spaces. In details **1 Tab = 4 Spaces** 

What do you think @kouroshD and @traversaro?

**Comment by traversaro** [comment]
That's a good idea. If you want, you can also add a clang-format file to simplify enforcing a given code style, including tabs/spaces. See https://github.com/robotology/sdf-modelica/pull/21 for a possible example of integration (but only just a `.clang-format` in the repo can be helpful.

**Comment by GiulioRomualdi** [comment]
Fixed in fe54681a8bfa6bd9275f9520d526e06d68bd0af1. You find further datails in #8
