### ISSUE TITLE
Do a new release

### ISSUE THREAD

**Issue by traversaro** [robotology/walking-teleoperation#68]
This is convenient to have a release compatible with hde v2.3.0, see https://github.com/robotology/robotology-superbuild/issues/861 .

**Comment by kouroshD** [comment]
Finally, the new version of walking teleoperation is released:
[v1.2.0](https://github.com/robotology/walking-teleoperation/releases/latest)
cc @traversaro  @S-Dafarra  @GiulioRomualdi
