### ISSUE TITLE
The virtualizer module stops with error "Virtualizer misscalibrated or disconnected"

### ISSUE THREAD

**Issue by S-Dafarra** [robotology/walking-teleoperation#74]
It fails with the error ``Virtualizer misscalibrated or disconnected``. Looking at https://github.com/robotology/walking-teleoperation/blob/9d13329716269ca1c44fefe225c38c83f1c27f79/modules/Virtualizer_module/src/VirtualizerModule.cpp#L372

I think that the problem is that the input angle jumps from +180 to -180.

cc @GiulioRomualdi @kouroshD

**Comment by kouroshD** [comment]
> playerYaw

No, that should not be a problem, because the angle is normalized here https://github.com/robotology/walking-teleoperation/blob/9d13329716269ca1c44fefe225c38c83f1c27f79/modules/Virtualizer_module/src/VirtualizerModule.cpp#L368

**Comment by S-Dafarra** [comment]
Yes, I double checked the values, and I was simply moving too fast. Maybe 0.15 is too small of a threshold?

**Comment by kouroshD** [comment]
That value is meant as a safety threshold when we are inside the virtualizer, off course with the hand we can move fast, but when we are inside virtualizer, it is hard to reach that value with the torso moving in a normal situation!

In any case, we can increase that value if necessary.

**Comment by S-Dafarra** [comment]
Ok let's keep it like this for the time being. Closing. Thanks @kouroshD for the support
