### ISSUE TITLE
Update GitHub actions

### ISSUE THREAD

**Issue by kouroshD** [robotology/walking-teleoperation#79]
It is since some time that we have not updated the GitHub actions.
We should add the option, when there is a change probably in one of the dependencies, we should run an action here as well.

**Comment by kouroshD** [comment]
Partially updated in this PR: https://github.com/robotology/walking-teleoperation/pull/72

Still HDE should be added, but it has more dependencies to compile.

**Comment by S-Dafarra** [comment]
With https://github.com/robotology/walking-teleoperation/pull/144 we switched to conda dependencies. Closing
