### ISSUE TITLE
Cleanup use of YARP deprecated methods

### ISSUE THREAD

**Issue by traversaro** [robotology/walking-teleoperation#95]
YARP deprecated methods such as `asDouble` are used in the codebase, for example in https://github.com/robotology/walking-teleoperation/blob/9d13329716269ca1c44fefe225c38c83f1c27f79/modules/Utils/src/Utils.cpp#L101 . That code will not compile once https://github.com/robotology/yarp/pull/2833 is merged.

**Comment by S-Dafarra** [comment]
Related PR https://github.com/robotology/walking-teleoperation/pull/97

**Comment by traversaro** [comment]
Fixed by https://github.com/robotology/walking-teleoperation/pull/97 .
